services:
  admin-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lodem-admin-app
    ports:
      - "${PORT:-5300}:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
